services:
  backend:
    container_name: backend
    build:
      context: ../nest-project
      dockerfile: ../newstack-docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../nest-project:/app
      - ../newstack-docker/backend/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    environment:
      - NODE_ENV=development

  frontend:
    container_name: frontend
    build:
      context: ../next-project
      dockerfile: ../newstack-docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../next-project:/app
      - ../newstack-docker/frontend/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - backend
