services:
  db:
    image: mysql:5.7
    container_name: saas_db
    command: >
      --innodb_flush_log_at_trx_commit=0 --innodb_buffer_pool_size=256M --innodb_log_buffer_size=16M --max_connections=1000 --sql_mode="" --skip-log-bin
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: saas
    volumes:
      - ../saas-database:/var/lib/mysql
    networks:
      - saas_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-padmin",
        ]
      timeout: 20s
      retries: 10

  api:
    build:
      context: ../saas-api
      dockerfile: ../saas-docker/api/Dockerfile
    container_name: saas_api
    volumes:
      - ../saas-api:/var/www
      - ../saas-docker/api/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_HOST: db
      DB_DATABASE: saas
      DB_USERNAME: root
      DB_PASSWORD: admin
    networks:
      - saas_network
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: saas_nginx
    ports:
      - "8000:80"
    volumes:
      - ../saas-api:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - saas_network

  frontend:
    build:
      context: ../saas-nuxt
      dockerfile: ../saas-docker/nuxt/Dockerfile
    container_name: saas_nuxt
    ports:
      - "3000:3000"
    volumes:
      - ../saas-nuxt:/app
      - ../saas-docker/nuxt/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - saas_network
    depends_on:
      - api

networks:
  saas_network:
    driver: bridge

volumes:
  vendor_volume:
